"""first tables

Revision: a55b21d7e912
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "a55b21d7e912"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_tenant_time", ["tenant_id", "created_at"], unique=False)

    op.create_table(
        "benchmark_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "guardrail_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("reply", sa.Text(), nullable=False),
        sa.Column("original_reply", sa.Text(), nullable=True),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("session_level", sa.String(length=10), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("shadow", sa.Boolean(), nullable=False),
        sa.Column("crisis", sa.Boolean(), nullable=False),
        sa.Column("rewritten", sa.Boolean(), nullable=False),
        sa.Column("from_fallback", sa.Boolean(), nullable=False),
        sa.Column("signals", sa.JSON(), nullable=False),
        sa.Column("issues", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guardrail_events", schema=None) as batch_op:
        batch_op.create_index("ix_events_tenant_session", ["tenant_id", "session_id"], unique=False)
        batch_op.create_index("ix_events_tenant_time", ["tenant_id", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_guardrail_events_risk_level"), ["risk_level"], unique=False
        )

    op.create_table(
        "policies",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("job_key", sa.String(length=300), nullable=False),
        sa.Column("scenario_id", sa.String(length=100), nullable=False),
        sa.Column("persona_id", sa.String(length=100), nullable=False),
        sa.Column("target_model", sa.String(length=200), nullable=False),
        sa.Column("guardrail", sa.Boolean(), nullable=False),
        sa.Column("repeat", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("transcript", sa.JSON(), nullable=True),
        sa.Column("guardrail_trace", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["benchmark_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "job_key"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_persona_id"), ["persona_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_conversations_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_conversations_scenario_id"), ["scenario_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_conversations_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_conversations_target_model"), ["target_model"], unique=False
        )

    op.create_table(
        "reviews",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("event_id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("reviewer", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["guardrail_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reviews_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "scores",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("conversation_id", sa.String(length=32), nullable=False),
        sa.Column("judge_model", sa.String(length=200), nullable=False),
        sa.Column("rubric_version", sa.String(length=20), nullable=False),
        sa.Column("measure_scores", sa.JSON(), nullable=False),
        sa.Column("turn_scores", sa.JSON(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scores")
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_tenant_id"))

    op.drop_table("reviews")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_target_model"))
        batch_op.drop_index(batch_op.f("ix_conversations_status"))
        batch_op.drop_index(batch_op.f("ix_conversations_scenario_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_run_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_persona_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_tenant_id"))

    op.drop_table("api_keys")
    op.drop_table("tenants")
    op.drop_table("policies")
    with op.batch_alter_table("guardrail_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guardrail_events_risk_level"))
        batch_op.drop_index("ix_events_tenant_time")
        batch_op.drop_index("ix_events_tenant_session")

    op.drop_table("guardrail_events")
    op.drop_table("benchmark_runs")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_tenant_time")

    op.drop_table("audit_log")
    # ### end Alembic commands ###
